### ISSUE TITLE
canot run project

### ISSUE THREAD

**Issue by bobwatcherx** [phoenixdev100/terabox-downloader#1]
when i run and run dev

C:\Users\LENOVO\Pictures\mainan\webdood\terabox-downloader>yarn dev
yarn run v1.22.21
warning package.json: No license field
error Command "dev" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

where you package.json file

**Comment by phoenixdev100** [comment]
try to run again and use 
npm install
npm run dev
fixed
let me know if u face any issue
